### ISSUE TITLE
Project Not Working

### ISSUE THREAD

**Issue by ghost** [s2online/s2online.github.io#3]
<p>    I'm not sure exactly what the issue is - but when a project that I upload that was made in 2.0 starts playing, instead of the flag waving, it just breaks into thirds and at first only one appears, then the second, then third, and then it resets.

**Comment by towerofnix** [comment]
That's interesting, I'll try to fix the problem! I'm not sure I 100% understand what you're describing here, though - when you said ""instead of the flag waving", are you talking about the green flag button pressed to start Scratch projects, or are you talking about a sprite that's inside your project?

It'll help me figure out what's causing the problem to happen if I can run the project myself. If you rename the file to end with ".zip" instead of ".sb2", you should be able to upload it into a GitHub comment here (click the "attach files" button at the bottom of the comment text input), and then I can download it and take a look.

**Comment by ghost** [comment]
It's https://scratch.mit.edu/projects/67026076/, I'm trying to make a remix of it that I'll move to the site, but it's not converting properly.  
[Go Norway! (2).zip](https://github.com/s2online/s2online.github.io/files/2827859/Go.Norway.2.zip)

**Comment by towerofnix** [comment]
Thanks for the link and file! So, I'm worried that the problem might be as simple as..it's just a project that causes a lot of lag. It appears to be loading into s2online correctly - but it lags pretty greatly when run (that's why the flag looks like it's ripped apart and appears in 3 steps). I'm wondering if this is a case of #4 - i.e, Stage3D, a technology Scratch uses to improve performance in some cases, not working. I noticed that if you remove the "draw" block, the project runs at proper speed (well, it doesn't display anything on the screen, of course, but the editor doesn't lag). So it looks like it has to do with drawing a lot of things on the screen at once. Note that when you run it in Scratch 3.0, it runs very smoothly -- that's because 3.0 has a very fast pen tool. But, usually Scratch 2.0 does too, so I wonder if it's a problem with Stage3D not working (it usually did in the online editor).

Sorry this doesn't give you a lot of direction as to how to fix this - I've created the issue #4 to keep track of investigation into why Stage3D doesn't work, which may help pen projects like this. But it probably isn't something I can fix very readily/quickly. The project seems to work well in Scratch 3.0, so you may be better off creating a remix in the 3.0 editor for now, if possible.

**Comment by ghost** [comment]
@towerofnix Alright, I'll edit it on 3.0! I just tried uploading it to s2online so that I could use the easier editor 👍

**Comment by towerofnix** [comment]
Alrighty! Best of luck with the project and getting used to 3.0 enough to work on it. :P - I'll close this issue since we can track Stage3D not working in that new issue I made.

**Comment by ghost** [comment]
@towerofnix :)
